apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qt2r9oobv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qt2r9oobv-nodejs 
  name: qt2r9oobv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qt2r9oobv-nodejs 
